services:
  - type: web
    name: resume-screening-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: flask db upgrade && flask seed && gunicorn run:app
    envVars:
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: production-secret-key-resume-screening-2026
      - key: DATABASE_URL
        value: mysql+pymysql://33AzvaX9rmmawum.root:7cbJrwDIjKnqXU7H@gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?ssl=true&ssl_verify_cert=false
      - key: STORAGE_TYPE
        value: local

