"""Add email models

Revision ID: 165825b15876
Revises: a2a1d326d683
Create Date: 2026-07-13 13:22:13.875012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '165825b15876'
down_revision = 'a2a1d326d683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('smtp_host', sa.String(length=120), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('sender_email', sa.String(length=120), nullable=True),
    sa.Column('sender_password', sa.String(length=120), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('candidate_name', sa.String(length=200), nullable=False),
    sa.Column('email_address', sa.String(length=120), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_history_candidate_id'), ['candidate_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_history_candidate_id'))

    op.drop_table('email_history')
    op.drop_table('email_settings')
    # ### end Alembic commands ###
