"""Add extraction_confidence to candidate

Revision ID: 52fff8c106b1
Revises: bf81a67946ab
Create Date: 2026-07-13 15:40:57.573692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52fff8c106b1'
down_revision = 'bf81a67946ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extraction_confidence', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('extraction_confidence')

    # ### end Alembic commands ###
