"""add authenticity and job enhancements

Revision ID: a2a1d326d683
Revises: 7e6745473971
Create Date: 2026-07-13 11:58:31.746561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2a1d326d683'
down_revision = '7e6745473971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_experience', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('min_qualification', sa.String(length=100), nullable=True))

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authenticity_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('authenticity_report', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_suspicious', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_column('is_suspicious')
        batch_op.drop_column('authenticity_report')
        batch_op.drop_column('authenticity_score')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('min_qualification')
        batch_op.drop_column('min_experience')

    # ### end Alembic commands ###
