"""Add explicit resume sections to candidate

Revision ID: bf81a67946ab
Revises: 276c8b9ea381
Create Date: 2026-07-13 15:09:57.620507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf81a67946ab'
down_revision = '276c8b9ea381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('career_objective', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('professional_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('technical_skills', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('soft_skills', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('education', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('experience', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('projects', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('certifications', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('languages', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('portfolio_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('portfolio_url')
        batch_op.drop_column('languages')
        batch_op.drop_column('certifications')
        batch_op.drop_column('projects')
        batch_op.drop_column('experience')
        batch_op.drop_column('education')
        batch_op.drop_column('soft_skills')
        batch_op.drop_column('technical_skills')
        batch_op.drop_column('professional_summary')
        batch_op.drop_column('career_objective')

    # ### end Alembic commands ###
